//! Compiled-header constant checks; result-status aliases are explicit.
use super::protocol::Record;
use swisseph_bindings::*;

/// Produce Rust constant values without parsing their numeric source literals.
pub fn rust_constants() -> Record {
    Record {
        op: 1001,
        ints: vec![
            JUL_CAL,                   // C: SE_JUL_CAL
            GREG_CAL,                  // C: SE_GREG_CAL
            ECL_NUT,                   // C: SE_ECL_NUT
            FIXSTAR,                   // C: SE_FIXSTAR
            SUN,                       // C: SE_SUN
            MOON,                      // C: SE_MOON
            MERCURY,                   // C: SE_MERCURY
            VENUS,                     // C: SE_VENUS
            MARS,                      // C: SE_MARS
            JUPITER,                   // C: SE_JUPITER
            SATURN,                    // C: SE_SATURN
            URANUS,                    // C: SE_URANUS
            NEPTUNE,                   // C: SE_NEPTUNE
            PLUTO,                     // C: SE_PLUTO
            MEAN_NODE,                 // C: SE_MEAN_NODE
            TRUE_NODE,                 // C: SE_TRUE_NODE
            MEAN_APOG,                 // C: SE_MEAN_APOG
            OSCU_APOG,                 // C: SE_OSCU_APOG
            EARTH,                     // C: SE_EARTH
            CHIRON,                    // C: SE_CHIRON
            PHOLUS,                    // C: SE_PHOLUS
            CERES,                     // C: SE_CERES
            PALLAS,                    // C: SE_PALLAS
            JUNO,                      // C: SE_JUNO
            VESTA,                     // C: SE_VESTA
            INTP_APOG,                 // C: SE_INTP_APOG
            INTP_PERG,                 // C: SE_INTP_PERG
            NPLANETS,                  // C: SE_NPLANETS
            PLMOON_OFFSET,             // C: SE_PLMOON_OFFSET
            AST_OFFSET,                // C: SE_AST_OFFSET
            VARUNA,                    // C: SE_VARUNA
            FICT_OFFSET,               // C: SE_FICT_OFFSET
            CUPIDO,                    // C: SE_CUPIDO
            HADES,                     // C: SE_HADES
            ZEUS,                      // C: SE_ZEUS
            KRONOS,                    // C: SE_KRONOS
            APOLLON,                   // C: SE_APOLLON
            ADMETOS,                   // C: SE_ADMETOS
            VULKANUS,                  // C: SE_VULKANUS
            POSEIDON,                  // C: SE_POSEIDON
            ISIS,                      // C: SE_ISIS
            NIBIRU,                    // C: SE_NIBIRU
            HARRINGTON,                // C: SE_HARRINGTON
            NEPTUNE_LEVERRIER,         // C: SE_NEPTUNE_LEVERRIER
            NEPTUNE_ADAMS,             // C: SE_NEPTUNE_ADAMS
            PLUTO_LOWELL,              // C: SE_PLUTO_LOWELL
            PLUTO_PICKERING,           // C: SE_PLUTO_PICKERING
            VULCAN,                    // C: SE_VULCAN
            WHITE_MOON,                // C: SE_WHITE_MOON
            PROSERPINA,                // C: SE_PROSERPINA
            WALDEMATH,                 // C: SE_WALDEMATH
            FLG_JPLEPH,                // C: SEFLG_JPLEPH
            FLG_SWIEPH,                // C: SEFLG_SWIEPH
            FLG_MOSEPH,                // C: SEFLG_MOSEPH
            FLG_HELCTR,                // C: SEFLG_HELCTR
            FLG_TRUEPOS,               // C: SEFLG_TRUEPOS
            FLG_J2000,                 // C: SEFLG_J2000
            FLG_NONUT,                 // C: SEFLG_NONUT
            FLG_SPEED3,                // C: SEFLG_SPEED3
            FLG_SPEED,                 // C: SEFLG_SPEED
            FLG_NOGDEFL,               // C: SEFLG_NOGDEFL
            FLG_NOABERR,               // C: SEFLG_NOABERR
            FLG_ASTROMETRIC,           // C: SEFLG_ASTROMETRIC
            FLG_EQUATORIAL,            // C: SEFLG_EQUATORIAL
            FLG_XYZ,                   // C: SEFLG_XYZ
            FLG_RADIANS,               // C: SEFLG_RADIANS
            FLG_BARYCTR,               // C: SEFLG_BARYCTR
            FLG_TOPOCTR,               // C: SEFLG_TOPOCTR
            FLG_SIDEREAL,              // C: SEFLG_SIDEREAL
            FLG_ICRS,                  // C: SEFLG_ICRS
            FLG_DEFAULTEPH,            // C: SEFLG_DEFAULTEPH
            SIDM_FAGAN_BRADLEY,        // C: SE_SIDM_FAGAN_BRADLEY
            SIDM_LAHIRI,               // C: SE_SIDM_LAHIRI
            SIDM_DELUCE,               // C: SE_SIDM_DELUCE
            SIDM_RAMAN,                // C: SE_SIDM_RAMAN
            SIDM_USHASHASHI,           // C: SE_SIDM_USHASHASHI
            SIDM_KRISHNAMURTI,         // C: SE_SIDM_KRISHNAMURTI
            SIDM_DJWHAL_KHUL,          // C: SE_SIDM_DJWHAL_KHUL
            SIDM_YUKTESHWAR,           // C: SE_SIDM_YUKTESHWAR
            SIDM_JN_BHASIN,            // C: SE_SIDM_JN_BHASIN
            SIDM_BABYL_KUGLER1,        // C: SE_SIDM_BABYL_KUGLER1
            SIDM_BABYL_KUGLER2,        // C: SE_SIDM_BABYL_KUGLER2
            SIDM_BABYL_KUGLER3,        // C: SE_SIDM_BABYL_KUGLER3
            SIDM_BABYL_HUBER,          // C: SE_SIDM_BABYL_HUBER
            SIDM_BABYL_ETPSC,          // C: SE_SIDM_BABYL_ETPSC
            SIDM_ALDEBARAN_15TAU,      // C: SE_SIDM_ALDEBARAN_15TAU
            SIDM_HIPPARCHOS,           // C: SE_SIDM_HIPPARCHOS
            SIDM_SASSANIAN,            // C: SE_SIDM_SASSANIAN
            SIDM_GALCENT_0SAG,         // C: SE_SIDM_GALCENT_0SAG
            SIDM_J2000,                // C: SE_SIDM_J2000
            SIDM_J1900,                // C: SE_SIDM_J1900
            SIDM_B1950,                // C: SE_SIDM_B1950
            SIDM_SURYASIDDHANTA,       // C: SE_SIDM_SURYASIDDHANTA
            SIDM_SURYASIDDHANTA_MSUN,  // C: SE_SIDM_SURYASIDDHANTA_MSUN
            SIDM_ARYABHATA,            // C: SE_SIDM_ARYABHATA
            SIDM_ARYABHATA_MSUN,       // C: SE_SIDM_ARYABHATA_MSUN
            SIDM_SS_REVATI,            // C: SE_SIDM_SS_REVATI
            SIDM_SS_CITRA,             // C: SE_SIDM_SS_CITRA
            SIDM_TRUE_CITRA,           // C: SE_SIDM_TRUE_CITRA
            SIDM_TRUE_REVATI,          // C: SE_SIDM_TRUE_REVATI
            SIDM_TRUE_PUSHYA,          // C: SE_SIDM_TRUE_PUSHYA
            SIDM_GALCENT_RGILBRAND,    // C: SE_SIDM_GALCENT_RGILBRAND
            SIDM_GALEQU_IAU1958,       // C: SE_SIDM_GALEQU_IAU1958
            SIDM_GALEQU_TRUE,          // C: SE_SIDM_GALEQU_TRUE
            SIDM_GALEQU_MULA,          // C: SE_SIDM_GALEQU_MULA
            SIDM_GALALIGN_MARDYKS,     // C: SE_SIDM_GALALIGN_MARDYKS
            SIDM_TRUE_MULA,            // C: SE_SIDM_TRUE_MULA
            SIDM_GALCENT_MULA_WILHELM, // C: SE_SIDM_GALCENT_MULA_WILHELM
            SIDM_ARYABHATA_522,        // C: SE_SIDM_ARYABHATA_522
            SIDM_BABYL_BRITTON,        // C: SE_SIDM_BABYL_BRITTON
            SIDM_TRUE_SHEORAN,         // C: SE_SIDM_TRUE_SHEORAN
            SIDM_GALCENT_COCHRANE,     // C: SE_SIDM_GALCENT_COCHRANE
            SIDM_GALEQU_FIORENZA,      // C: SE_SIDM_GALEQU_FIORENZA
            SIDM_VALENS_MOON,          // C: SE_SIDM_VALENS_MOON
            SIDM_LAHIRI_1940,          // C: SE_SIDM_LAHIRI_1940
            SIDM_LAHIRI_VP285,         // C: SE_SIDM_LAHIRI_VP285
            SIDM_KRISHNAMURTI_VP291,   // C: SE_SIDM_KRISHNAMURTI_VP291
            SIDM_LAHIRI_ICRC,          // C: SE_SIDM_LAHIRI_ICRC
            SIDM_USER,                 // C: SE_SIDM_USER
            NODBIT_MEAN,               // C: SE_NODBIT_MEAN
            NODBIT_OSCU,               // C: SE_NODBIT_OSCU
            NODBIT_OSCU_BAR,           // C: SE_NODBIT_OSCU_BAR
            NODBIT_FOPOINT,            // C: SE_NODBIT_FOPOINT
            CALC_RISE,                 // C: SE_CALC_RISE
            CALC_SET,                  // C: SE_CALC_SET
            CALC_MTRANSIT,             // C: SE_CALC_MTRANSIT
            CALC_ITRANSIT,             // C: SE_CALC_ITRANSIT
            BIT_GEOCTR_NO_ECL_LAT,     // C: SE_BIT_GEOCTR_NO_ECL_LAT
            BIT_DISC_CENTER,           // C: SE_BIT_DISC_CENTER
            BIT_NO_REFRACTION,         // C: SE_BIT_NO_REFRACTION
            BIT_CIVIL_TWILIGHT,        // C: SE_BIT_CIVIL_TWILIGHT
            BIT_NAUTIC_TWILIGHT,       // C: SE_BIT_NAUTIC_TWILIGHT
            BIT_ASTRO_TWILIGHT,        // C: SE_BIT_ASTRO_TWILIGHT
            BIT_DISC_BOTTOM,           // C: SE_BIT_DISC_BOTTOM
            BIT_FIXED_DISC_SIZE,       // C: SE_BIT_FIXED_DISC_SIZE
            BIT_FORCE_SLOW_METHOD,     // C: SE_BIT_FORCE_SLOW_METHOD
            BIT_HINDU_RISING,          // C: SE_BIT_HINDU_RISING
            ECL2HOR,                   // C: SE_ECL2HOR
            EQU2HOR,                   // C: SE_EQU2HOR
            HOR2ECL,                   // C: SE_HOR2ECL
            HOR2EQU,                   // C: SE_HOR2EQU
            TRUE_TO_APP,               // C: SE_TRUE_TO_APP
            APP_TO_TRUE,               // C: SE_APP_TO_TRUE
            ECL_CENTRAL,               // C: SE_ECL_CENTRAL
            ECL_NONCENTRAL,            // C: SE_ECL_NONCENTRAL
            ECL_TOTAL,                 // C: SE_ECL_TOTAL
            ECL_ANNULAR,               // C: SE_ECL_ANNULAR
            ECL_PARTIAL,               // C: SE_ECL_PARTIAL
            ECL_ANNULAR_TOTAL,         // C: SE_ECL_ANNULAR_TOTAL
            ECL_HYBRID,                // C: SE_ECL_HYBRID
            ECL_PENUMBRAL,             // C: SE_ECL_PENUMBRAL
            ECL_ALLTYPES_SOLAR,        // C: SE_ECL_ALLTYPES_SOLAR
            ECL_ALLTYPES_LUNAR,        // C: SE_ECL_ALLTYPES_LUNAR
            ECL_VISIBLE,               // C: SE_ECL_VISIBLE
            ECL_MAX_VISIBLE,           // C: SE_ECL_MAX_VISIBLE
            ECL_1ST_VISIBLE,           // C: SE_ECL_1ST_VISIBLE
            ECL_PARTBEG_VISIBLE,       // C: SE_ECL_PARTBEG_VISIBLE
            ECL_2ND_VISIBLE,           // C: SE_ECL_2ND_VISIBLE
            ECL_TOTBEG_VISIBLE,        // C: SE_ECL_TOTBEG_VISIBLE
            ECL_3RD_VISIBLE,           // C: SE_ECL_3RD_VISIBLE
            ECL_TOTEND_VISIBLE,        // C: SE_ECL_TOTEND_VISIBLE
            ECL_4TH_VISIBLE,           // C: SE_ECL_4TH_VISIBLE
            ECL_PARTEND_VISIBLE,       // C: SE_ECL_PARTEND_VISIBLE
            ECL_PENUMBBEG_VISIBLE,     // C: SE_ECL_PENUMBBEG_VISIBLE
            ECL_PENUMBEND_VISIBLE,     // C: SE_ECL_PENUMBEND_VISIBLE
            ECL_OCC_BEG_DAYLIGHT,      // C: SE_ECL_OCC_BEG_DAYLIGHT
            ECL_OCC_END_DAYLIGHT,      // C: SE_ECL_OCC_END_DAYLIGHT
            ECL_ONE_TRY,               // C: SE_ECL_ONE_TRY
            HELIACAL_RISING,           // C: SE_HELIACAL_RISING
            HELIACAL_SETTING,          // C: SE_HELIACAL_SETTING
            MORNING_FIRST,             // C: SE_MORNING_FIRST
            EVENING_LAST,              // C: SE_EVENING_LAST
            EVENING_FIRST,             // C: SE_EVENING_FIRST
            MORNING_LAST,              // C: SE_MORNING_LAST
            HELFLAG_LONG_SEARCH,       // C: SE_HELFLAG_LONG_SEARCH
            HELFLAG_HIGH_PRECISION,    // C: SE_HELFLAG_HIGH_PRECISION
            HELFLAG_OPTICAL_PARAMS,    // C: SE_HELFLAG_OPTICAL_PARAMS
            HELFLAG_NO_DETAILS,        // C: SE_HELFLAG_NO_DETAILS
            HELFLAG_SEARCH_1_PERIOD,   // C: SE_HELFLAG_SEARCH_1_PERIOD
            HELFLAG_VISLIM_DARK,       // C: SE_HELFLAG_VISLIM_DARK
            HELFLAG_VISLIM_NOMOON,     // C: SE_HELFLAG_VISLIM_NOMOON
            HELFLAG_VISLIM_PHOTOPIC,   // C: SE_HELFLAG_VISLIM_PHOTOPIC
            HELFLAG_VISLIM_SCOTOPIC,   // C: SE_HELFLAG_VISLIM_SCOTOPIC
            HELFLAG_AV,                // C: SE_HELFLAG_AV
            HELFLAG_AVKIND_VR,         // C: SE_HELFLAG_AVKIND_VR
            HELFLAG_AVKIND_PTO,        // C: SE_HELFLAG_AVKIND_PTO
            HELFLAG_AVKIND_MIN7,       // C: SE_HELFLAG_AVKIND_MIN7
            HELFLAG_AVKIND_MIN9,       // C: SE_HELFLAG_AVKIND_MIN9
            HELFLAG_AVKIND,            // C: SE_HELFLAG_AVKIND
            HELFLAG_BELOW_HORIZON,     // C: (-2)
            HELFLAG_PHOTOPIC,          // C: SE_PHOTOPIC_FLAG
            HELFLAG_SCOTOPIC,          // C: SE_SCOTOPIC_FLAG
            HELFLAG_MIXED,             // C: SE_MIXEDOPIC_FLAG
            PHOTOPIC_FLAG,             // C: SE_PHOTOPIC_FLAG
            SCOTOPIC_FLAG,             // C: SE_SCOTOPIC_FLAG
            MIXEDOPIC_FLAG,            // C: SE_MIXEDOPIC_FLAG
            SPLIT_DEG_ROUND_SEC,       // C: SE_SPLIT_DEG_ROUND_SEC
            SPLIT_DEG_ROUND_MIN,       // C: SE_SPLIT_DEG_ROUND_MIN
            SPLIT_DEG_ROUND_DEG,       // C: SE_SPLIT_DEG_ROUND_DEG
            SPLIT_DEG_ZODIACAL,        // C: SE_SPLIT_DEG_ZODIACAL
            SPLIT_DEG_NAKSHATRA,       // C: SE_SPLIT_DEG_NAKSHATRA
            SPLIT_DEG_KEEP_SIGN,       // C: SE_SPLIT_DEG_KEEP_SIGN
            SPLIT_DEG_KEEP_DEG,        // C: SE_SPLIT_DEG_KEEP_DEG
            ACRONYCHAL_RISING,         // C: SE_ACRONYCHAL_RISING
            ACRONYCHAL_SETTING,        // C: SE_ACRONYCHAL_SETTING
            COSMICAL_SETTING,          // C: SE_COSMICAL_SETTING
            COMET_OFFSET,              // C: SE_COMET_OFFSET
            FICT_MAX,                  // C: SE_FICT_MAX
            FICT_OFFSET_1,             // C: SE_FICT_OFFSET_1
            DE_NUMBER,                 // C: SE_DE_NUMBER
            FLG_CENTER_BODY,           // C: SEFLG_CENTER_BODY
            ASC,                       // C: SE_ASC
            MC,                        // C: SE_MC
            ARMC,                      // C: SE_ARMC
            VERTEX,                    // C: SE_VERTEX
            EQUASC,                    // C: SE_EQUASC
            COASC1,                    // C: SE_COASC1
            COASC2,                    // C: SE_COASC2
        ],
        floats: vec![
            SE_TIDAL_DE200,           // C: SE_TIDAL_DE200
            SE_TIDAL_DE403,           // C: SE_TIDAL_DE403
            SE_TIDAL_DE404,           // C: SE_TIDAL_DE404
            SE_TIDAL_DE405,           // C: SE_TIDAL_DE405
            SE_TIDAL_DE406,           // C: SE_TIDAL_DE406
            SE_TIDAL_DE421,           // C: SE_TIDAL_DE421
            SE_TIDAL_DE422,           // C: SE_TIDAL_DE422
            SE_TIDAL_DE430,           // C: SE_TIDAL_DE430
            SE_TIDAL_DE431,           // C: SE_TIDAL_DE431
            SE_TIDAL_DE441,           // C: SE_TIDAL_DE441
            SE_TIDAL_26,              // C: SE_TIDAL_26
            SE_TIDAL_STEPHENSON_2016, // C: SE_TIDAL_STEPHENSON_2016
            SE_TIDAL_DEFAULT,         // C: SE_TIDAL_DEFAULT
            SE_TIDAL_AUTOMATIC,       // C: SE_TIDAL_AUTOMATIC
            SE_TIDAL_MOSEPH,          // C: SE_TIDAL_MOSEPH
            SE_TIDAL_SWIEPH,          // C: SE_TIDAL_SWIEPH
            SE_TIDAL_JPLEPH,          // C: SE_TIDAL_JPLEPH
            SE_DELTAT_AUTOMATIC,      // C: SE_DELTAT_AUTOMATIC
            TJD_INVALID,              // C: TJD_INVALID
            AUNIT_TO_KM,              // C: SE_AUNIT_TO_KM
            AUNIT_TO_LIGHTYEAR,       // C: SE_AUNIT_TO_LIGHTYEAR
            AUNIT_TO_PARSEC,          // C: SE_AUNIT_TO_PARSEC
        ],
        texts: vec![
            ASTNAMFILE.as_bytes().to_vec(), // C: SE_ASTNAMFILE
            FICTFILE.as_bytes().to_vec(),   // C: SE_FICTFILE
        ],
        ..Record::default()
    }
}
